---
- name: Create a security group
  amazon.aws.ec2_security_group:
    name: "{{ security_group_name }}"
    description: "{{ security_group_description }}"
    region: "{{ cloud_location }}"
    rules:
      - proto: "{{ item.protocol }}"
        from_port: "{{ item.port }}"
        to_port: "{{ item.port }}"
        cidr_ip: "{{ item.cidr }}"
    state: present
  with_items: "{{ ingress_ports }}"
  register: security_group

- name: Create an EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    instance_type: "{{ instance_type }}"
    region: "{{ cloud_location }}"
    image_id: "{{ instance_image }}"
    wait: "{{ wait_for_ssh | bool }}"
    instance_tags:
      Name: "{{ instance_tag }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: "{{ storage_size }}"
    network:
      assign_public_ip: "{{ public_ip }}"
      groups: "{{ security_group.group_id }}"
  register: ec2

- name: Wait for the instance to be reachable via SSH
  ansible.builtin.wait_for:
    host: "{{ ec2.instances[0].public_ip_address }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  when: wait_for_ssh | bool

- name: Add instance to inventory
  ansible.builtin.add_host:
    name: "{{ ec2.instances[0].public_ip_address }}"
    groups: "{{ instance_tag }}"
    ansible_host: "{{ ec2.instances[0].public_ip_address }}"
    ansible_user: "{{ cloud_user }}"
    ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
