---
- name: Create a firewall
  community.digitalocean.digital_ocean_firewall:
    oauth_token: "{{ do_token }}"
    state: present
    name: "{{ do_firewall_name }}"
    inbound_rules:
      - protocol: "{{ item.protocol }}"
        port_range: "{{ item.port }}"
        source_addresses: "{{ item.cidr }}"
  with_items: "{{ ingress_ports }}"
  register: firewall

- name: Create a DigitalOcean droplet
  community.digitalocean.digital_ocean_droplet:
    oauth_token: "{{ do_token }}"
    name: "{{ instance_tag }}"
    region: "{{ do_region }}"
    size: "{{ do_size }}"
    image: "{{ do_image }}"
    ssh_keys: ["{{ do_ssh_key_fingerprint }}"]
    wait: "{{ wait_for_ssh | bool }}"
    tags: [ "{{ instance_tag }}" ]
  register: do_droplet

- name: Wait for the instance to be reachable via SSH
  ansible.builtin.wait_for:
    host: "{{ do_droplet.data.ip_address }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  when: wait_for_ssh | bool

- name: Add instance to inventory
  ansible.builtin.add_host:
    name: "{{ do_droplet.data.ip_address }}"
    groups: "{{ instance_tag }}"
    ansible_host: "{{ do_droplet.data.ip_address }}"
    ansible_user: root
    ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
