---
- name: Check for uninstall signal
  ansible.builtin.command: /bin/true
  notify: Uninstall
  when: uninstall | bool

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup cloud provider node
  ansible.builtin.include_tasks: "./{{ cloud_provider }}.yml"
  when: not uninstall | bool
